a=int(input("enter a int number:"))
b=float(input("enter a float number:"))
c=str(input("enter a string:"))
d=bool(input("enter a boolean value:"))
e=complex(input("enter a complex number:"))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))